version: "3.9"
services:
  django:
    container_name: joham_web
    build: 
      context: .
    ports:
      - "8001:8000"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.joham-web.rule=Host(`joham.dev`, `www.joham.dev`)"
      - traefik.http.routers.joham-web.entrypoints=websecure
      - traefik.http.routers.joham-web.tls=true
    networks:
      - traefik
networks:
  traefik:
    external: true
